site_name: Ashish Satapathy
repo_name: arsatapathy/mkdocs-resume
repo_url: https://github.com/arsatapathy/mkdocs-resume
site_url: https://arsatapathy.github.io/mkdocs-resume

nav: 
  - Home: index.md

theme:
    name: dracula
    logo: assets/img/ashish_profile_photo.png

search:
  disable: true