site_name: Ashish Satapathy
site_url: https://arsatapathy.github.io/mkdocs-test

nav: 
  - Home: index.md

theme:
    name: dracula
    logo: assets/img/ashish_profile_photo.png

extra:
  social:
    - icon: fontawesome/solid/code
      link: https://github.com/arsatapathy/mkdocs-resume
      text: View source code